import { useState, useEffect, useRef } from "react";

const THEMES = [
  "Heavy Metal", "Smooth Jazz", "Classical Piano", "Country Ballad", "Gospel Choir",
  "Death Metal", "Bossa Nova", "Bluegrass", "K-Pop", "Afrobeats",
  "Reggaeton", "Drill Rap", "Lo-Fi Hip Hop", "Indie Folk", "Synthwave",
  "Dancehall", "Deep House", "Punk Rock", "Ambient Techno", "Flamenco",
  "Delta Blues", "Trap Music", "Barbershop Quartet", "Doo-Wop", "Neo Soul",
  "Grunge", "New Wave", "Chillwave", "Vaporwave", "Psychedelic Rock", "Soft Rock", "Hard Rock",
  "Emo", "Post-Punk", "Math Rock", "Midwest Emo", "Pop Punk", "Ska", "Reggae", "Cumbia",
  "Merengue", "Salsa", "Tejano", "Norteño", "Mariachi", "Celtic Folk", "Viking Metal",
  "J-Pop", "City Pop", "Bedroom Pop", "Dream Pop", "Shoegaze", "Noise Rock", "Post-Rock",
  "Art Rock", "Progressive Rock", "Funk", "Disco", "R&B", "Motown", "Soul", "Zydeco", "Cajun",
  "Appalachian Folk", "Sea Shanty", "Gregorian Chant", "Opera", "Musical Theatre",
  "Spoken Word", "Slam Poetry", "Stadium Concert", "Jazz Bar at Midnight", "Open Mic Night",
  "Festival Main Stage", "Dive Bar Karaoke", "Church Choir", "Subway Busker", "Rooftop DJ Set",
  "Tiny Desk Concert", "Drive-In Concert", "Symphony Hall", "Outdoor Amphitheatre",
  "Basement Show", "House Party DJ", "Beach Bonfire Singalong", "Elevator Music",
  "Dentist Office Radio", "Supermarket Muzak", "Club at 2AM", "Warm-Up Act",
  "Festival Side Stage", "Hotel Lobby Piano", "Cruise Ship Show Band", "State Fair",
  "High School Battle of the Bands", "Open Air Festival", "Drum Solo", "Bass Drop",
  "Guitar Hero Shredding", "Violin Virtuoso", "Trumpet Jazz Solo", "Piano Ballad",
  "Acoustic Guitar Serenade", "DJ Turntables", "Theremin Performance", "Ukulele Cover",
  "Banjo Breakdown", "Sax Solo", "Harp Solo", "Cello Suite", "Beatboxing", "A Cappella Group",
  "One-Man Band", "Air Guitar Champion", "Finger Drumming", "Lip Sync Battle",
  "Recording Studio Session", "Mixing the Final Master", "Beat Making at 3AM",
  "Sampling a Vinyl Record", "Auto-Tune Heavy", "Raw Acoustic Recording",
  "Vocal Booth Warm-Up", "Producer's Demo Tape", "Lo-Fi Tape Recording",
  "Sound Engineer's Nightmare", "Triple-Tracked Guitars", "Layered Harmonies",
  "Drum Machine Programming", "Field Recording", "Live Studio Take", "Pre-Game Hype Playlist",
  "Crying to a Breakup Song", "Gym Workout Banger", "Late Night Study Music",
  "Morning Commute Playlist", "Road Trip Sing-Along", "First Dance at a Wedding",
  "Funeral Hymn", "Lullaby for a Baby", "Rage Against the Speakers", "Slow Dance in the Kitchen",
  "Headphones In, World Out", "Guilty Pleasure Pop Song", "Song Stuck in Your Head",
  "Misheard Lyrics", "Wrong Playlist Moment", "Shuffle Mode Surprise", "Skip Every Song",
  "Repeat One All Day", "Song That Makes You Cry", "Song That Brings You Joy",
  "First Song at the Club", "Last Song of the Night", "Driving Too Fast to This",
  "Crying in the Car", "Grammy Acceptance Speech", "Album Release Day", "Chart-Topping Single",
  "One Hit Wonder", "Comeback Album", "Debut EP Drop", "Going Platinum", "B-Side Deep Cut",
  "Hidden Track", "Leaked Album", "Music Video Shoot", "Press Tour Interview",
  "World Tour Bus Life", "Backstage Rider Demands", "Meet & Greet Line", "Record Label Drama",
  "Signing a Record Deal", "Going Independent", "Sold-Out Tour", "Cancelled Tour",
  "Surprise Drop", "Concept Album", "Double Album", "Live Album Recording", "Unplugged Special",
  "Covers Album", "60s Beatlemania", "70s Disco Fever", "80s Power Ballad", "90s Boy Band",
  "00s Pop Princess", "10s EDM Festival", "20s Bedroom Producer", "Woodstock 1969",
  "Punk Revolution 1977", "Grunge Era Seattle", "Rave Scene 1992", "Napster Era",
  "MTV Total Request Live", "Radio Countdown Show", "Cassette Tape Rewind",
  "CD Booklet Reading", "Vinyl Record Flip Side", "Streaming Era", "Algorithm Playlist",
  "Power Ballad Key Change", "Four-Chord Pop Song", "Verse-Chorus-Bridge",
  "The Guitar Solo That Goes On Too Long", "When the Drop Hits", "Unexpected Time Signature",
  "Song in a Minor Key", "Modulating to a Higher Key", "The Bridge Nobody Sings Along To",
  "Extended Outro", "Thirty-Second Intro", "Slow Intro Fast Song", "Quiet Verse Loud Chorus",
  "The Breakdown Section", "Finger Snap Beat", "Hand Clap Rhythm", "Whistling Hook",
  "Call and Response", "Spoken Word Interlude", "Orchestra Swell", "Fade Out Ending",
  "Cold Stop Ending", "Reprise at the End", "Overture", "Medley", "Knowing Every Lyric",
  "Singing the Wrong Words Confidently", "Air Drumming in Public", "Concert Merch Queue",
  "Defending Your Favourite Artist", "Gatekeeping a Band", "Introducing a Friend to a New Genre",
  "Obsessing Over an Album", "Overplaying a Song Until You Hate It",
  "Rediscovering an Old Favourite", "Live Show Disappointment", "Life-Changing Concert",
  "Crowd Surfing", "Mosh Pit Survivor", "Lighter in the Air", "Phone Flashlight at a Ballad",
  "Waiting for the Encore", "Leaving Before the Last Song", "Front Row Standing",
  "Watching from the Back",
];
